spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        jdbc:
          lob:
            non_contextual_creation: true

  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/risk-db
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver